export { default as SantanderIcon } from "./SantanderIcon"
export { default as DffrntIcon } from "./DffrntIcon"
export { default as Acclr8Icon } from "./Acclr8Icon"
export { default as UOBIcon } from "./UOBIcon"
export { default as RoyalAcademyEngineering } from "./RoyalAcademyEngineering"
export { default as BE } from "./BE"
export { default as QuoteMark } from "./QuoteMark"
